import type { Metadata } from "next";
import { Navbar } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ padding: "0px", margin: "0px" }}>
      <body style={{ padding: "0px", margin: "0px" }}>
        <div className="layout">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
